# Generated by Django 5.1.1 on 2024-09-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='division',
        ),
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office'),
        ),
    ]
