# Generated by Django 5.1.1 on 2024-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
