# Generated by Django 5.1.1 on 2024-09-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('suggestions', models.TextField()),
                ('client_type', models.CharField(choices=[('CM', 'Citizen (Mamayan)'), ('B', 'Business'), ('G', 'Government (Employee or another agency)')], max_length=2)),
                ('cc1', models.IntegerField(choices=[(1, "I know what a CC is and I saw this office's CC. (Alam ko ang ibig sabihin ng CC at nakita ko na ito.)"), (2, "I know what a CC is but I did NOT see this office's CC. (Alam ko ang ibig sabihin ng CC ngunit hindi ko pa ito nakita.)"), (3, "I learned of the CC only when I saw this office's CC. (Natutunan ko kung ano ang CC nung nakita ko ito.)"), (4, 'I do not know what a CC is and I did not see one in this office. (Hindi ko alam kung ano ang CC at hindi ko pa ito nakikita.)')])),
                ('cc2', models.IntegerField(choices=[(1, 'Easy to see (Madaling Makita)'), (2, 'Somewhat easy to see (Medyo madaling makita)'), (3, 'Difficult to see (Mahirap makita)'), (4, 'Not visible at all (Hindi talaga nakikita)'), (5, 'N/A (Hindi na-aangkop)')])),
                ('cc3', models.IntegerField(choices=[(1, 'Helped very much (Nakatulong ng lubusan)'), (2, 'Somewhat helped (Bahagyang nakatulong)'), (3, 'Did not help (Hindi ito nakatulong)'), (4, 'N/A (Hindi na-aangkop)')])),
                ('sqd0', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd1', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd2', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd3', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd4', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd5', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd6', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd7', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
                ('sqd8', models.IntegerField(choices=[(0, 'N/A'), (1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')])),
            ],
        ),
    ]
