# Generated by Django 5.1.1 on 2024-09-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='service',
            field=models.IntegerField(choices=[(1, 'Service 1'), (2, 'Service 2'), (3, 'Service 3'), (4, 'Service 4')]),
        ),
    ]
