# Generated by Django 5.1.1 on 2024-09-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_department_survey_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='department',
        ),
    ]
