# Generated by Django 5.1.1 on 2024-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_survey_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_description',
            field=models.TextField(blank=True, help_text='Enter a description of the department (e.g., its purpose or functions)', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='service',
            field=models.IntegerField(choices=[('Basic Services', [(1, 'Service 1'), (2, 'Service 2')]), ('Premium Services', [(3, 'Service 3'), (4, 'Service 4')])]),
        ),
    ]
