# Generated by Django 5.1.1 on 2024-09-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_department_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.department'),
        ),
    ]
