# Generated by Django 5.1.1 on 2024-09-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=254)),
                ('division_name_description', models.TextField(blank=True, help_text='Enter a description of the division', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='department',
        ),
        migrations.AddField(
            model_name='survey',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cc1',
            field=models.IntegerField(choices=[(1, "I know what a CC is and I saw this office's CC."), (2, "I know what a CC is but I did NOT see this office's CC."), (3, "I learned of the CC only when I saw this office's CC."), (4, 'I do not know what a CC is and I did not see one in this office.')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cc2',
            field=models.IntegerField(choices=[(1, 'Easy to see'), (2, 'Somewhat easy to see'), (3, 'Difficult to see'), (4, 'Not visible at all'), (5, 'N/A')]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='cc3',
            field=models.IntegerField(choices=[(1, 'Helped very much'), (2, 'Somewhat helped'), (3, 'Did not help'), (4, 'N/A')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.division'),
        ),
        migrations.AddField(
            model_name='survey',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.division'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
