# Generated by Django 5.1.1 on 2024-09-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_division_remove_profile_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
