# Generated by Django 5.1.1 on 2024-09-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_division_profile_office'),
        ('office', '0001_initial'),
        ('survey', '0012_alter_service_division_alter_survey_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='division',
        ),
        migrations.RemoveField(
            model_name='service',
            name='division',
        ),
        migrations.AddField(
            model_name='service',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office'),
        ),
        migrations.AddField(
            model_name='survey',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
