# Generated by Django 5.1.1 on 2024-09-20 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_remove_service_office'),
        ('survey', '0014_alter_survey_service_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=254)),
                ('service_description', models.TextField(blank=True, help_text='Enter a description of the service', null=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.office')),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.service'),
        ),
    ]
