# Generated by Django 5.1.1 on 2024-09-26 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_service'),
        ('survey', '0016_alter_survey_service_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.office'),
        ),
    ]
