# Generated by Django 5.1.1 on 2024-09-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_alter_survey_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
