# Generated by Django 5.1.1 on 2024-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=254)),
                ('office_description', models.TextField(blank=True, help_text='Enter a description of the office', null=True)),
            ],
        ),
    ]
