# Generated by Django 5.1.1 on 2024-09-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='office',
        ),
    ]
