# Generated by Django 5.1.1 on 2024-09-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_remove_service_office'),
        ('survey', '0015_service_alter_survey_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
